name: demonstration-hosting-deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to IONOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          delete_remote_files: true
          local_path: './src/'
          remote_path: '/pages/9to5/demo/'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}
