name: Deploy to IONOS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH
      run: apt-get update && apt-get install -y openssh-client
    - name: Upload files to IONOS
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        local-dir: ./.github/
        server-dir: /9to5/
        protocol: sftp
